# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_878dlcq6ne/clone/recipe, last modified Tue Apr 30 08:20:16 2024
# ------------------------------------------------

package:
  name: fmt
  version: 9.1.0
source:
  sha256: 5dea48d1fcddc3ec571ce2058e13910a0d4a6bab4cc09a809d8b1dd1c88ae6f2
  url: https://github.com/fmtlib/fmt/archive/9.1.0.tar.gz
build:
  number: '1'
  run_exports:
    - fmt >=9.1.0,<10.0a0
  string: h48ca7d4_1
requirements:
  build:
    - bzip2 1.0.8 h80987f9_5
    - c-ares 1.19.1 h80987f9_0
    - ca-certificates 2024.3.11 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - cmake 3.26.4 h5d7ac33_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.6.2 h313beb8_0
    - krb5 1.20.1 hf3e1bf2_1
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcurl 8.5.0 h3e2b118_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20230828 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.4 hca03da5_0
    - libllvm14 14.0.6 h7ec7a93_3
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.10.0 h02f6b3c_2
    - libuv 1.44.2 h80987f9_0
    - llvm-tools 14.0.6 hfd8c8a6_3
    - lz4-c 1.9.4 h313beb8_0
    - ncurses 6.4 h313beb8_0
    - ninja 1.10.2 hca03da5_5
    - ninja-base 1.10.2 h525c30c_5
    - openssl 3.0.13 h1a28f6b_0
    - python 3.12.3 h99e199e_0
    - readline 8.2 h1a28f6b_0
    - rhash 1.4.3 h02f6b3c_0
    - sqlite 3.41.2 h80987f9_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2024a h04d1e81_0
    - xz 5.4.6 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
    - zstd 1.5.5 hd90d995_0
  host:
    - libcxx 14.0.6 h848a8c0_0
  run:
    - libcxx >=14.0.6
test:
  commands:
    - test -d ${PREFIX}/include/fmt
    - test -f ${PREFIX}/include/fmt/core.h
    - test -f ${PREFIX}/include/fmt/format.h
    - test -f ${PREFIX}/lib/cmake/fmt/fmt-config.cmake
    - test -f ${PREFIX}/lib/libfmt.dylib
about:
  description: '{fmt} is an open-source formatting library for C++.

    It can be used as a safe and fast alternative to (s)printf and iostreams.

    '
  dev_url: https://github.com/fmtlib/fmt
  doc_url: https://fmt.dev/latest/
  home: https://fmt.dev/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: '{fmt} is an open-source formatting library for C++'
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 876ef710-1ec2-4d3d-ba8d-3436ffb2cf11
  recipe-maintainers:
    - saraedum
    - tdegeus
    - vitaut
  remote_url: git@github.com:AnacondaRecipes/fmt-feedstock.git
  sha: 7cb8975f287d62155c34c438933167a8fdb42ec9
