# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_03b1up8uh3/clone/recipe, last modified Tue Jul 29 02:36:31 2025
# ------------------------------------------------

package:
  name: tomli
  version: 2.2.1
source:
  sha256: cd45e1dc79c835ce60f7404ec8119f2eb06d38b1deba146f07ced3bbc44505ff
  url: https://pypi.io/packages/source/t/tomli/tomli-2.2.1.tar.gz
build:
  number: '0'
  script: /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_03b1up8uh3/croot/tomli_1753774598375/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - flit-core 3.9.0 py313hf651a9f_1
    - libcxx 17.0.6 he5c5206_4
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.17 h4ee41c1_0
    - pip 25.1 pyhc872135_2
    - python 3.13.5 h2eb94d5_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 78.1.1 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.14 h6ba3021_1
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('tomli')=='2.2.1')"
  files:
    - example.toml
  imports:
    - tomli
  requires:
    - pip
about:
  description: Tomli is a Python library for parsing TOML. It is fully compatible
    with TOML v1.0.0.
  dev_url: https://github.com/hukkin/tomli
  doc_url: https://github.com/hukkin/tomli/blob/master/README.md
  home: https://github.com/hukkin/tomli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple TOML parser
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 03201ec3-ab7e-4814-835e-a222ca935859
  recipe-maintainers:
    - thewchan
  remote_url: git@github.com:AnacondaRecipes/tomli-feedstock.git
  sha: 69323bd5dfccc885317e49e70b6582797af8ed65
