# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_e8rxq5w44p/clone/recipe, last modified Thu Jul 31 11:47:40 2025
# ------------------------------------------------

package:
  name: anaconda-anon-usage
  version: 0.7.2
source:
  sha256: b4b6c2d17a2ab7907b0e5e7846d7522f7a09a21c1ddd575aeae55c506b7d4e27
  url: https://github.com/anaconda/anaconda-anon-usage/archive/refs/tags/0.7.2.tar.gz
build:
  number: '100'
  script_env:
    - NEED_SCRIPTS=no
  string: py313hd6b623d_100
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 17.0.6 he5c5206_4
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.17 h4ee41c1_0
    - pip 25.1 pyhc872135_2
    - python 3.13.5 h2eb94d5_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 78.1.1 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.14 h6ba3021_1
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - conda >=23.7
test:
  commands:
    - pip check
    - conda info
    - conda info --json
  imports:
    - anaconda_anon_usage
  requires:
    - conda >=23.7
    - pip
about:
  description: 'This package augments the request header data that conda delivers

    to package servers during index and package requests. Specifically,

    three randomly generated tokens are appended to the "user agent"

    that Conda already sends with each request.

    '
  dev_url: https://github.com/anaconda/anaconda-anon-usage/
  doc_url: https://github.com/anaconda/anaconda-anon-usage/
  home: https://github.com/anaconda/anaconda-anon-usage
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: basic anonymous telemetry for conda clients
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e85079d8-f1df-4a54-8324-13953b471968
  remote_url: git@github.com:AnacondaRecipes/anaconda-anon-usage-feedstock.git
  sha: 3f93d725faccd9e67f3d8a374f0c0f419b12d909
