# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: c-ares
  version: 1.34.5
source:
  sha256: dcd919635f01b7c8c9c2f5fb38063cd86500f7c6d4d32ecf4deff5e3497fb157
  url: https://github.com/c-ares/c-ares/archive/refs/tags/v1.34.5.tar.gz
build:
  number: 0
  run_exports:
    - c-ares >=1.34.5,<2.0a0
  string: h2ca31fc_0
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.7.15 hca03da5_0
    - cctools_osx-arm64 949.0.1 h69e4071_26
    - clang 14.0.6 hca03da5_2
    - clang-14 14.0.6 default_h1b80db6_2
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_2
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - cmake-no-system 3.25.3 h313beb8_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.7.1 h313beb8_0
    - gtest 1.14.0 h48ca7d4_1
    - ld64_osx-arm64 530 hac4b543_26
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_2
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - libmpdec 4.0.0 h80987f9_0
    - llvm-tools 14.0.6 h7ec7a93_4
    - macosx_deployment_target_osx-arm64 11.1 had524d6_1
    - ncurses 6.5 hee39554_0
    - ninja 1.12.1 hca03da5_0
    - ninja-base 1.12.1 h48ca7d4_0
    - openssl 3.0.17 h4ee41c1_0
    - python 3.13.5 h2eb94d5_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.3 h0b18652_0
    - sqlite 3.50.2 h79febb2_1
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  host:
    - libcxx 19.1.7 hb09ecce_3
  run:
    - __osx >=11.1
    - libcxx >=14.0.6
  run_constraint:
    - c-ares-static <0a0
test:
  commands:
    - test -f ${PREFIX}/include/ares.h
    - test -f ${PREFIX}/lib/libcares${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcares.a
    - test ! -f ${PREFIX}/lib/libcares_static.a
about:
  description: 'c-ares is a C library for asynchronous DNS requests (including name
    resolves).

    '
  dev_url: https://github.com/c-ares/c-ares
  doc_url: https://c-ares.org/docs.html
  home: https://c-ares.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 2704fd5f-51cd-446a-92ee-62b9c2aaf210
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/c-ares-feedstock.git
  sha: 1f96936549a27938581187393a8b8143bded04c2
