# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_be9at15ui5/clone/recipe, last modified Thu Apr 24 03:51:36 2025
# ------------------------------------------------

package:
  name: keyring
  version: 25.6.0
source:
  sha256: 0b39998aa941431eb3d9b0d4b2460bc773b9df6fed7621c2dfb291a7e0187a66
  url: https://pypi.io/packages/source/k/keyring/keyring-25.6.0.tar.gz
build:
  entry_points:
    - keyring = keyring.cli:main
  number: '0'
  script: /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_be9at15ui5/croot/keyring_1745484704517/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.16 h02f6b3c_0
    - packaging 24.2 py313hca03da5_0
    - pip 25.0 py313hca03da5_0
    - python 3.13.2 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 75.8.0 py313hca03da5_0
    - setuptools-scm 8.2.1 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2025a h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - jaraco.classes
    - jaraco.context
    - jaraco.functools
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - shtab >= 1.1.0
test:
  commands:
    - pip check
    - keyring --help
  imports:
    - keyring
    - keyring.backends
    - keyring.util
  requires:
    - pip
    - pytest >=6,!=8.1.*
  source_files:
    - tests/*
about:
  description: 'The python keyring lib provides a easy way to access the system keyring

    service from python.  it can be used in any application that needs safe

    password storage.

    '
  dev_url: https://github.com/jaraco/keyring
  doc_url: https://pypi.org/project/keyring/
  home: https://github.com/jaraco/keyring
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Store and access your passwords safely
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: be2bf950-6c40-483d-ae9f-0d4e74e0c096
  recipe-maintainers:
    - ccordoba12
    - licode
    - tacaswell
  remote_url: git@github.com:AnacondaRecipes/keyring-feedstock.git
  sha: 2be65f709e62805dc3eb5d37c1e3280b9f632c12
