# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /Users/builder/cbouss/perseverance-python-buildout/aggregate/colorama-feedstock/recipe, last modified Tue Oct  8 11:27:22 2024
# ------------------------------------------------

package:
  name: colorama
  version: 0.4.6
source:
  sha256: 08695f5cb7ed6e0531a20572697297273c47b8cae5a63ffc6d6ed5c201be6e44
  url: https://pypi.io/packages/source/c/colorama/colorama-0.4.6.tar.gz
build:
  number: '0'
  script: /Users/builder/cbouss/perseverance-python-buildout/croot/colorama_1728588725923/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.9.24 hca03da5_0
    - expat 2.6.3 h313beb8_0
    - hatchling 1.25.0 py313hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - packaging 24.1 py313hca03da5_0
    - pathspec 0.10.3 py313hca03da5_0
    - pip 24.2 py313hca03da5_0
    - pluggy 1.0.0 py313hca03da5_1
    - python 3.13.0 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 75.1.0 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - trove-classifiers 2023.10.18 py313hca03da5_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py313hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
  imports:
    - colorama
  requires:
    - pip
about:
  description: 'colorama is a cross-platform colored terminal text.It makes

    ANSI escape character sequences (for producing colored terminal text

    and cursor positioning) work under MS Windows.

    '
  dev_url: https://github.com/tartley/colorama
  doc_url: https://pypi.org/project/colorama/
  home: https://github.com/tartley/colorama
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Cross-platform colored terminal text
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - kwilcox
    - ocefpaf
