# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_91zaq5_008/clone/recipe, last modified Mon Feb 24 08:41:54 2025
# ------------------------------------------------

package:
  name: jaraco.functools
  version: 4.1.0
source:
  sha256: 70f7e0e2ae076498e212562325e805204fc092d7b4c17e0e86c959e249701a9d
  url: https://pypi.org/packages/source/j/jaraco.functools/jaraco_functools-4.1.0.tar.gz
build:
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_91zaq5_008/croot/jaraco.functools_1740408121405/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.12.31 hca03da5_0
    - expat 2.6.4 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - packaging 24.2 py313hca03da5_0
    - pip 25.0 py313hca03da5_0
    - python 3.13.2 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 75.8.0 py313hca03da5_0
    - setuptools-scm 8.1.0 py313hca03da5_0
    - setuptools_scm 8.1.0 hd3eb1b0_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2025a h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - more-itertools
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - pytest -vv test_functools.py -k "not test_function_throttled"
  imports:
    - jaraco.functools
  requires:
    - jaraco.classes
    - pip
    - pytest
  source_files:
    - test_functools.py
about:
  dev_url: https://github.com/jaraco/jaraco.functools
  doc_url: https://github.com/jaraco/jaraco.functools
  home: https://github.com/jaraco/jaraco.functools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Additional functools in the spirit of stdlib's functools.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 91bba777-d24c-44f1-aa7d-5447f5447208
  recipe-maintainers:
    - carlodri
  remote_url: git@github.com:AnacondaRecipes/jaraco.functools-feedstock.git
  sha: 3d4fd6597492367b8e219648b4baf7f8be3583c8
