# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_46bi6cbtd0/clone/recipe, last modified Fri Nov 29 08:38:18 2024
# ------------------------------------------------

package:
  name: libssh2
  version: 1.11.1
source:
  sha256: d9ec76cbe34db98eec3539fe2c899d26b0c837cb3eb466a56b0f109cabf658f7
  url: https://www.libssh2.org/download/libssh2-1.11.1.tar.gz
build:
  number: '0'
  run_exports:
    - libssh2 >=1.11.1,<2.0a0
  string: h3e2b118_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - cmake-no-system 3.25.3 h313beb8_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - llvm-tools 14.0.6 h7ec7a93_4
    - ninja-base 1.12.1 h48ca7d4_0
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host:
    - ca-certificates 2024.11.26 hca03da5_0
    - openssl 3.0.15 h80987f9_0
    - zlib 1.2.13 h18a0788_1
  run:
    - openssl >=3.0.15,<4.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f $PREFIX/include/libssh2.h
    - test -f $PREFIX/include/libssh2_publickey.h
    - test -f $PREFIX/include/libssh2_sftp.h
    - test -f $PREFIX/lib/libssh2${SHLIB_EXT}
    - test -f $PREFIX/lib/pkgconfig/libssh2.pc
about:
  description: 'libssh2 is a library implementing the SSH2 protocol, available under
    the revised BSD license.

    '
  dev_url: https://github.com/libssh2/libssh2
  doc_url: https://www.libssh2.org/docs.html
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 469ad8db-b29c-43ff-a8ef-513fdbbb866c
  recipe-maintainers:
    - shadowwalkersb
  remote_url: git@github.com:AnacondaRecipes/libssh2-feedstock.git
  sha: ccf17c18a57eafac668302e8b68bd89ce4526611
