# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: spdlog
  version: 1.11.0
source:
  sha256: ca5cae8d6cac15dae0ec63b21d6ad3530070650f68076f3a4a862ca293a858bb
  url: https://github.com/gabime/spdlog/archive/v1.11.0.tar.gz
build:
  number: 0
  run_exports:
    - spdlog >=1.11.0,<2.0a0
  string: h48ca7d4_0
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - c-ares 1.18.1 h1a28f6b_0
    - ca-certificates 2023.01.10 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - cmake 3.22.1 hae769c0_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.4.9 hc377ac9_0
    - krb5 1.19.4 h8380606_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcurl 7.87.0 h0f1d93c_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20221030 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.2 hca03da5_6
    - libllvm14 14.0.6 h7ec7a93_1
    - libnghttp2 1.46.0 h95c9599_0
    - libssh2 1.10.0 hf27765b_0
    - libuv 1.39.0 h1a28f6b_0
    - llvm-tools 14.0.6 h7ec7a93_1
    - lz4-c 1.9.4 h313beb8_0
    - ncurses 6.4 h313beb8_0
    - ninja 1.10.2 hca03da5_5
    - ninja-base 1.10.2 h525c30c_5
    - openssl 1.1.1t h1a28f6b_0
    - python 3.11.0 hc0d8a6c_2
    - readline 8.2 h1a28f6b_0
    - rhash 1.4.1 hf27765b_1
    - sqlite 3.40.1 h7a7dc30_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022g h04d1e81_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
    - zstd 1.5.2 h8574219_0
  host:
    - fmt 9.1.0 h48ca7d4_0
    - libcxx 14.0.6 h848a8c0_0
  run:
    - fmt >=9.1.0,<10.0a0
    - libcxx >=14.0.6
test:
  commands:
    - test -e $PREFIX/include/spdlog/spdlog.h
about:
  description: 'spdlog is a header only library for Super fast C++ logging

    to be used with a C++11 compiler.

    '
  dev_url: https://github.com/gabime/spdlog
  doc_url: https://github.com/gabime/spdlog/wiki/1.-QuickStart
  home: https://github.com/gabime/spdlog
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Super fast C++ logging library.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e2ab125b-f2fa-4c8f-90c9-f656defceeea
  recipe-maintainers:
    - bluescarni
    - druvus
    - rongou
  remote_url: git@github.com:AnacondaRecipes/spdlog-feedstock.git
  sha: ce0071cb793cfd6c85f53a912eadb9a51d786988
