# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_034myiu7pr/clone/recipe, last modified Tue Nov 26 10:36:15 2024
# ------------------------------------------------

package:
  name: rich
  version: 13.9.4
source:
  sha256: 22bfd7f24f6107ed222f6ab0cee6f0016e22cb6f91144b90c65b112663c7477c
  url: https://github.com/Textualize/rich/archive/refs/tags/v13.9.4.tar.gz
build:
  number: '0'
  script: /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_034myiu7pr/croot/rich_1732638981241/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.9.24 hca03da5_0
    - expat 2.6.3 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - pip 24.2 py313hca03da5_0
    - poetry-core 1.5.1 py313hca03da5_0
    - python 3.13.0 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 75.1.0 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py313hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - markdown-it-py >=2.2.0
    - pygments >=2.13.0,<3.0.0
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - ipywidgets >=7.5.1,<9
test:
  commands:
    - pip check
    - pytest -vv tests -k "not (test_markdown_render or test_syntax_highlight_ranges
      or test_option_no_wrap or test_python_render or test_card_render or test_brokenpipeerror
      or test_background_color_override_includes_padding)"
  imports:
    - rich
  requires:
    - attrs
    - pip
    - pytest
  source_files:
    - tests
about:
  description: "Rich is a Python library for rich text and beautiful formatting\n\
    in the terminal.The Rich API makes it easy to add color and style to\nterminal\
    \ output. Rich can also render pretty tables, progress bars,\nmarkdown, syntax\
    \ highlighted source code, tracebacks, and more \u2014 out\nof the box.\n"
  dev_url: https://github.com/Textualize/rich
  doc_url: https://rich.readthedocs.io/en/latest/
  home: https://github.com/Textualize/rich
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rich is a Python library for rich text and beautiful formatting in the
    terminal.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 03008992-ca36-40d3-90b0-47ee366652bc
  recipe-maintainers:
    - jan-janssen
    - willmcgugan
  remote_url: git@github.com:AnacondaRecipes/rich-feedstock.git
  sha: 0654e705fbbc3865fac02cb5c4b7df1cd72f37da
