# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_54q0wtkt6i/clone/recipe, last modified Wed Mar 29 04:26:57 2023
# ------------------------------------------------

package:
  name: nlohmann_json
  version: 3.11.2
source:
  sha256: d69f9deb6a75e2580465c6c4c5111b89c4dc2fa94e3a85fcd2ffcd9a143d9273
  url: https://github.com/nlohmann/json/archive/v3.11.2.tar.gz
build:
  ignore_run_exports:
    - libcxx
    - libgcc-ng
    - libstdcxx-ng
    - vc
    - vs2015_runtime
  number: '0'
  string: h313beb8_0
requirements:
  build:
    - bzip2 1.0.8 h620ffc9_4
    - c-ares 1.19.0 h80987f9_0
    - ca-certificates 2023.01.10 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_0
    - clang-14 14.0.6 default_hf5194b7_0
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_hf5194b7_0
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - cmake 3.22.1 hae769c0_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.4.9 hc377ac9_0
    - krb5 1.19.4 h8380606_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_hf5194b7_0
    - libcurl 7.88.1 h0f1d93c_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20221030 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.2 hca03da5_6
    - libllvm14 14.0.6 h7ec7a93_1
    - libnghttp2 1.46.0 h95c9599_0
    - libssh2 1.10.0 hf27765b_0
    - libuv 1.44.2 h80987f9_0
    - llvm-tools 14.0.6 h7ec7a93_1
    - lz4-c 1.9.4 h313beb8_0
    - ncurses 6.4 h313beb8_0
    - ninja 1.10.2 hca03da5_5
    - ninja-base 1.10.2 h525c30c_5
    - openssl 1.1.1t h1a28f6b_0
    - python 3.11.2 hc0d8a6c_0
    - readline 8.2 h1a28f6b_0
    - rhash 1.4.1 hf27765b_1
    - sqlite 3.41.1 h80987f9_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2022g h04d1e81_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
    - zstd 1.5.4 hd90d995_0
  host: []
  run: []
test:
  commands:
    - test -d ${PREFIX}/include/nlohmann
    - test -f ${PREFIX}/include/nlohmann/json.hpp
    - test -f ${PREFIX}/include/nlohmann/json_fwd.hpp
    - test -f ${PREFIX}/share/cmake/nlohmann_json/nlohmann_jsonConfig.cmake
    - test -f ${PREFIX}/share/cmake/nlohmann_json/nlohmann_jsonConfigVersion.cmake
    - test -f ${PREFIX}/share/cmake/nlohmann_json/nlohmann_jsonTargets.cmake
about:
  description: JSON for Modern C++ is a C++11 JSON parser.
  dev_url: https://github.com/nlohmann/json
  doc_url: https://nlohmann.github.io/json/
  home: https://github.com/nlohmann/json
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: JSON for Modern C++
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 549e7f89-a3fd-4881-871d-55d50d8a753b
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - constantinpape
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/nlohmann_json-feedstock.git
  sha: d5caab31d1166826079c5a35fe4802b173f56d57
