# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_2fwl36f6cv/clone/recipe, last modified Wed Oct  9 10:15:44 2024
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.6
source:
  patches:
    - patches/4019.patch
  sha256: 30f35f71c1203369dc979ecde0400ffea93c27391bfd2ac5a9715d2173d92ff7
  url: https://github.com/facebook/zstd/archive/v1.5.6.tar.gz
build:
  number: '0'
  run_exports:
    - zstd >=1.5.6,<1.6.0a0
  string: hfb09047_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 14.0.6 h1d3d883_0
    - cmake-no-system 3.25.3 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - make 4.3 h620ffc9_1
    - ninja-base 1.10.2 h525c30c_5
    - patch 2.7.6 h1a28f6b_1001
  host:
    - libcxx 14.0.6 h848a8c0_0
    - lz4-c 1.9.4 h313beb8_1
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - lz4-c >=1.9.4,<1.10.0a0
    - xz >=5.4.6,<6.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - zstd -be -i5
    - test -f ${PREFIX}/include/zstd.h
    - test -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/lib/libzstd.dylib
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - pkg-config --cflags libzstd
  requires:
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: https://facebook.github.io/zstd/
  license: BSD-3-Clause AND GPL-2.0-or-later
  license_family: BSD
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 2f743577-ee38-46f6-8f68-ad4bd4e33ce1
  recipe-maintainers:
    - chenghlee
    - msarahan
    - rmax
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/zstd-feedstock.git
  sha: 0bec3d8794a5154155101d8f1bb2f7e4cae0ba0d
