# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /Users/builder/cbouss/perseverance-python-buildout/aggregate/shellingham-feedstock/recipe, last modified Tue Oct  8 11:32:13 2024
# ------------------------------------------------

package:
  name: shellingham
  version: 1.5.0
source:
  sha256: 72fb7f5c63103ca2cb91b23dee0c71fe8ad6fbfd46418ef17dbe40db51592dad
  url: https://pypi.io/packages/source/s/shellingham/shellingham-1.5.0.tar.gz
build:
  number: '0'
  script: /Users/builder/cbouss/perseverance-python-buildout/croot/shellingham_1728591266231/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps -vv
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.9.24 hca03da5_0
    - expat 2.6.3 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - pip 24.2 py313hca03da5_0
    - python 3.13.0 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 75.1.0 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py313hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
  imports:
    - shellingham
    - shellingham.posix
  requires:
    - pip
about:
  description: Shellingham detects what shell the current Python executable is running
    in.
  dev_url: https://github.com/sarugaku/shellingham/tree/master
  doc_url: https://github.com/sarugaku/shellingham#readme
  home: https://github.com/sarugaku/shellingham
  license: ISC
  license_family: OTHER
  license_url: https://github.com/sarugaku/shellingham/blob/master/LICENSE
  summary: Tool to Detect Surrounding Shell
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
