# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: libcxx
  version: 19.1.7
source:
  - patches:
      - patches/0001-disable-_LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPT.patch
      - patches/0002-Work-around-stray-nostdlib-flags-causing-errors-with.patch
      - patches/0003-patch-__libcpp_tzdb_directory-to-allow-use-on-osx.patch
    sha256: 82401fea7b79d0078043f7598b835284d6650a75b93e64b6f761ea7b63097501
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/llvm-project-19.1.7.src.tar.xz
build:
  ignore_run_exports_from:
    - clang_bootstrap_osx-arm64 19.*
  number: 3
  string: hb09ecce_3
requirements:
  build:
    - clang_bootstrap_osx-arm64 19.1.7 h310783a_2
    - macosx_deployment_target_osx-arm64 11.1 had524d6_1
  host:
    - __osx >=11.1
  run:
    - __osx >=11.1
  run_constrained:
    - clang 19.1.7
    - llvm 19.1.7
    - llvm-openmp  19.1.7
    - llvm-tools  19.1.7
test:
  commands:
    - test -f $PREFIX/lib/libc++.1.dylib
    - test ! -L $PREFIX/lib/libc++.dylib
    - test ! -d $PREFIX/include/c++
    - test ! -f $PREFIX/lib/libc++.a
about:
  description: 'libc++ is an implementation of the C++ standard library developed
    by the LLVM project.

    It supports C++11, C++14, C++17, and parts of C++20.

    This package also includes libc++abi, which provides the low-level runtime support
    needed

    by libc++, including exception handling and other ABI-related features.

    '
  dev_url: https://github.com/llvm/llvm-project
  doc_url: https://libcxx.llvm.org/
  home: https://libcxx.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: libcxx/LICENSE.TXT
  summary: LLVM C++ standard library
extra:
  copy_test_source_files: true
  feedstock-name: libcxx
  final: true
  flow_run_id: c53a809e-3559-4a0b-b191-c0646d635cf0
  recipe-maintainers:
    - SylvainCorlay
    - beckermr
    - h-vetinari
    - inducer
    - isuruf
    - jakirkham
    - timsnyder
  remote_url: git@github.com:AnacondaRecipes/libcxx-feedstock.git
  sha: 21204275a5423f50e02b0d3e4015c697e3a3f3ed
  skip-lints:
    - should_use_compilers
