{% set version = "0.8.6" %}

package:
  name: anaconda-cloud-auth-split
  version: {{ version }}

source:
  git_url: https://github.com/anaconda/anaconda-auth.git
  git_tag: v{{ version }}

build:
  number: 0
  # noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  skip: True  # [py<39]

requirements:
  build:
    - git   # [not win]

outputs:
  - name: anaconda-auth
    build:
      script: python -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
    requirements:
      build:
        - git   # [not win]
      host:
        - python
        - hatchling
        - hatch-vcs >=0.3
        - pip
        - setuptools-scm >=7.1
      run:
        - python
        - anaconda-cli-base >=0.5.2
        - cryptography >=3.4.0
        - keyring
        - pkce
        - pydantic
        - pyjwt
        - python-dotenv
        - requests
        - semver <4
      run_constrained:
        - conda >=23.9.0
        - conda-token >=0.6.0
        - anaconda-cloud-auth >=0.8.2
    test:
      source_files:
        - pyproject.toml
      requires:
        - pip
      imports:
        - anaconda_auth
      commands:
        - pip check
        - python -c "from anaconda_auth import __version__; assert __version__ == '{{ version }}'"

  - name: anaconda-cloud-auth
    requirements:
      build:
        - git   # [not win]
      host:
        - python
        - {{ pin_subpackage("anaconda-auth", exact=True) }}
      run:
        - python
        - {{ pin_subpackage("anaconda-auth", exact=True) }}
    test:
      source_files:
        - pyproject.toml
      imports:
        - anaconda_auth
        - anaconda_cloud_auth
      source_files:
        - tests
      requires:
        - pip
        - pytest
        - pytest-mock
        - responses
        - types-requests
      commands:
        - pip check
        - anaconda -h
        - anaconda -V
        - anaconda cloud --help
        - anaconda cloud -V
        - python -c "from anaconda_cloud_auth import __version__; assert __version__ == \"{{ version }}\""

about:
  home: https://anaconda.com
  doc_url: https://anaconda.github.io/anaconda-auth/
  dev_url: https://github.com/anaconda/anaconda-auth
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client auth library for Anaconda.cloud APIs
  description: |
    A client library for Anaconda.cloud APIs to authenticate and securely store API keys.
    This package also provides a requests client class that handles loading the API key
    for requests made to Anaconda Cloud services.

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
