# This file created by conda-build 3.26.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_5f_fb0pad4/clone/recipe, last modified Thu Aug 17 12:23:57 2023
# ------------------------------------------------

package:
  name: icu
  version: '73.1'
source:
  - patches:
      - icu-22356.patch
      - mach-port-t.patch
    sha256: a457431de164b4aa7eca00ed134d00dfbf88a77c6986a10ae7774fc076bb8c45
    url: https://github.com/unicode-org/icu/releases/download/release-73-1/icu4c-73_1-src.tgz
  - folder: source/data
    sha256: 07d7557efb30fc2e9b74652f1525603b3209a4539d2d345d704e3df3bf9b957e
    url: https://github.com/unicode-org/icu/releases/download/release-73-1/icu4c-73_1-data.zip
build:
  number: '0'
  run_exports:
    - icu >=73.1,<74.0a0
  string: h313beb8_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_0
    - libllvm14 14.0.6 h7ec7a93_3
    - libtool 2.4.6 h313beb8_1009
    - llvm-tools 14.0.6 hfd8c8a6_3
    - make 4.3 h620ffc9_1
    - patch 2.7.6 h1a28f6b_1001
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - libcxx 14.0.6 h848a8c0_0
  run:
    - libcxx >=14.0.6
test:
  commands:
    - test -f $PREFIX/lib/libicudata.a
    - test -f $PREFIX/lib/libicudata.73.1.dylib
    - test -f $PREFIX/lib/libicui18n.a
    - test -f $PREFIX/lib/libicui18n.73.1.dylib
    - test -f $PREFIX/lib/libicuio.a
    - test -f $PREFIX/lib/libicuio.73.1.dylib
    - test -f $PREFIX/lib/libicutest.a
    - test -f $PREFIX/lib/libicutest.73.1.dylib
    - test -f $PREFIX/lib/libicutu.a
    - test -f $PREFIX/lib/libicutu.73.1.dylib
    - test -f $PREFIX/lib/libicuuc.a
    - test -f $PREFIX/lib/libicuuc.73.1.dylib
    - genbrk --help
    - gencfu --help
    - gencnval --help
    - gendict --help
    - icuinfo --help
    - icu-config --help
    - makeconv gb-18030-2000.ucm
    - genrb de.txt
    - echo "de.res" > list.txt
    - pkgdata -p mybundle list.txt
  files:
    - de.txt
    - gb-18030-2000.ucm
about:
  description: 'ICU is a mature, widely used set of C/C++ and Java libraries providing

    Unicode and Globalization support for software applications. ICU is

    widely portable and gives applications the same results on all platforms

    and between C/C++ and Java software.

    '
  dev_url: https://github.com/unicode-org/icu
  doc_url: https://unicode-org.github.io/icu/
  home: https://icu.unicode.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: International Components for Unicode.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 5f77ed87-9f28-4b53-a707-ccc02a1bfe33
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/icu-feedstock.git
  sha: be820b07c5e0bff9e01e173920897db1b55e815a
