# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_barck9k8fe/clone/recipe, last modified Thu Aug  7 07:44:03 2025
# ------------------------------------------------

package:
  name: certifi
  version: 2025.8.3
source:
  - folder: certifi
    sha256: fdbe80c4c92fc99449759a62e06508667eabbdb04f1ace6010b88028de8d2c97
    url: https://github.com/certifi/python-certifi/archive/refs/tags/2025.08.03.tar.gz
  - folder: pip_wheel
    sha256: 3790624780082365f47549d032f3770eeb2b1e8bd1f7b2e02dace1afa361b4ed
    url: https://pypi.io/packages/py3/p/pip/pip-24.3.1-py3-none-any.whl
  - folder: setuptools_wheel
    sha256: ce74b49e8f7110f9bf04883b730f4765b774ef3ef28f722cce7c273d253aaf7d
    url: https://pypi.io/packages/py3/s/setuptools/setuptools-75.6.0-py3-none-any.whl
build:
  number: '0'
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 17.0.6 he5c5206_4
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.17 h4ee41c1_0
    - python 3.13.5 h2eb94d5_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.3 h0b18652_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.14 h6ba3021_1
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('certifi')=='2025.8.3')"
    - pytest -vv certifi/certifi/tests
  imports:
    - certifi
  requires:
    - pip
    - pytest
  source_files:
    - certifi/certifi/tests
about:
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  dev_url: https://github.com/certifi/python-certifi
  doc_url: https://github.com/certifi/python-certifi/blob/master/README.rst
  home: https://certifi.io
  license: MPL-2.0
  license_family: Other
  license_file: certifi/LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ba99d8df-9c19-4aa7-999d-e8840bd95024
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/certifi-feedstock.git
  sha: 4532e15c0b89b8ccedcd0382fe490182d04abf9c
  skip-lints:
    - missing_python_build_tool
