# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /Users/builder/cbouss/buildout/aggregate/wheel-feedstock/recipe, last modified Thu Feb 13 14:00:05 2025
# ------------------------------------------------

package:
  name: wheel
  version: 0.45.1
source:
  sha256: 661e1abd9198507b1409a20c02106d9670b2576e916d58f520316666abca6729
  url: https://pypi.io/packages/source/w/wheel/wheel-0.45.1.tar.gz
build:
  entry_points:
    - wheel = wheel.cli:main
  number: '0'
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.12.31 hca03da5_0
    - expat 2.6.4 h313beb8_0
    - flit-core 3.9.0 py313hf651a9f_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - python 3.13.2 h4862095_100_cp313
    - python-installer 0.7.0 pyhd3eb1b0_1
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2025a h04d1e81_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - wheel --help
    - wheel version
  imports:
    - wheel
    - wheel.cli
    - wheel.vendored
    - wheel.vendored.packaging
  requires:
    - pip
about:
  description: "This library is the reference implementation of the Python wheel packaging\
    \ standard,\nas defined in PEP 427.\nIt has two different roles:\n  1. A setuptools\
    \ extension for building wheels that provides the bdist_wheel setuptools command\n\
    \  2. A command line tool for working with wheel files\n"
  dev_url: https://github.com/pypa/wheel
  doc_url: https://wheel.readthedocs.io/
  home: https://github.com/pypa/wheel
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
  skip-lints:
    - missing_wheel
