# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_9d3ads2bae/clone/recipe, last modified Tue Jun 24 03:45:37 2025
# ------------------------------------------------

package:
  name: pydantic-core
  version: 2.33.2
source:
  sha256: 7cb8bc3605c29176e1b105350d2e6474142d7c1bd1d9327c4a9bdb46bf827acc
  url: https://pypi.org/packages/source/p/pydantic-core/pydantic_core-2.33.2.tar.gz
build:
  number: '0'
  script:
    - /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_9d3ads2bae/croot/pydantic-core_1750754745671/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
      -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  script_env: null
  string: py313h5e3a92f_0
requirements:
  build:
    - cargo-bundle-licenses 0.5.0 ha6e5c4f_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_2
    - clang-14 14.0.6 default_h1b80db6_2
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_2
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_2
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - llvm-tools 14.0.6 h7ec7a93_4
    - rust 1.87.0 h313beb8_0
    - rust_osx-arm64 1.87.0 h313beb8_0
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 17.0.6 he5c5206_3
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - maturin 1.8.6 py313h2aea54e_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.16 h02f6b3c_0
    - pip 25.1 pyhc872135_2
    - python 3.13.5 h2eb94d5_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 78.1.1 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_1
    - typing-extensions 4.12.2 py313hca03da5_0
    - typing_extensions 4.12.2 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - typing-extensions >=4.6.0,!=4.7.0
test:
  commands:
    - pip check
    - python -c "from pydantic_core import PydanticUndefinedType"
  imports:
    - pydantic_core
  requires:
    - pip
about:
  description: 'This package provides the core functionality for pydantic validation
    and serialization.

    '
  dev_url: https://github.com/pydantic/pydantic-core
  doc_url: https://docs.pydantic.dev
  home: https://github.com/pydantic/pydantic-core
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Core validation logic for pydantic written in rust
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9d4e58f5-90cf-4994-a5a5-62ae8320020c
  recipe-maintainers:
    - adriangb
    - dmontagu
    - pavelzw
    - samuelcolvin
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/pydantic-core-feedstock.git
  sha: 0a015eeaaacd9608135bf6e10e1db0dd40d56eaa
