# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_bei6q1cvvt/clone/recipe, last modified Mon Dec  2 14:00:09 2024
# ------------------------------------------------

package:
  name: pluggy
  version: 1.5.0
source:
  fn: pluggy-1.5.0.tar.gz
  sha256: 2cffa88e94fdc978c4c574f15f9e59b7f4201d439195c3715ca9e2486f1d0cf1
  url: https://pypi.io/packages/source/p/pluggy/pluggy-1.5.0.tar.gz
build:
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_bei6q1cvvt/croot/pluggy_1733169621717/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.11.26 hca03da5_0
    - expat 2.6.3 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - packaging 24.1 py313hca03da5_0
    - pip 24.2 py313hca03da5_0
    - python 3.13.0 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 75.1.0 py313hca03da5_0
    - setuptools-scm 8.1.0 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py313hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
  imports:
    - pluggy
  requires:
    - pip
about:
  description: 'pluggy is the crystallized core of plugin management and hook calling
    for pytest.

    It enables 1400+ plugins to extend and customize pytest''s default behaviour.

    Even pytest itself is composed as a set of pluggy plugins which are invoked

    in sequence according to a well defined set of protocols.

    '
  dev_url: https://github.com/pytest-dev/pluggy/
  doc_url: https://pluggy.readthedocs.io
  home: https://github.com/pytest-dev/pluggy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Plugin registration and hook calling for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: be67f9f5-0327-4584-a0fe-cd1c0b2b66f1
  recipe-maintainers:
    - JohnGreeley
    - nicoddemus
  remote_url: git@github.com:AnacondaRecipes/pluggy-feedstock.git
  sha: b0f2ea667d8b73e7e013107fc3f4116807eb0339
