# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /Users/builder/cbouss/perseverance-python-buildout/aggregate/distro-feedstock/recipe, last modified Tue Oct  8 11:27:48 2024
# ------------------------------------------------

package:
  name: distro
  version: 1.9.0
source:
  fn: distro-1.9.0.tar.gz
  sha256: 2fa77c6fd8940f116ee1d6b94a2f90b13b5ea8d019b98bc8bafdcabcdd9bdbed
  url: https://pypi.io/packages/source/d/distro/distro-1.9.0.tar.gz
build:
  entry_points:
    - distro = distro.distro:main
  number: '0'
  script: /Users/builder/cbouss/perseverance-python-buildout/croot/distro_1728591855492/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -v --no-build-isolation
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.9.24 hca03da5_0
    - expat 2.6.3 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - pip 24.2 py313hca03da5_0
    - python 3.13.0 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 75.1.0 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py313hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - distro --help
  imports:
    - distro
  requires:
    - pip
about:
  description: distro provides information about the OS distribution it runs on, such
    as a reliable machine-readable ID, or version information.
  dev_url: https://github.com/python-distro/distro
  doc_url: https://distro.readthedocs.io
  home: https://github.com/python-distro/distro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A much more elaborate replacement for removed Python's 'platform.linux_distribution()'
    method
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - abloemert
    - windelbouwman
