# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: python
  version: 3.13.5
source:
  - patches:
      - patches/0000-branding.patch
      - patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0002-Win32-Do-not-download-externals.patch
      - patches/0003-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0004-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0005-Unvendor-openssl.patch
      - patches/0006-Unvendor-sqlite3.patch
      - patches/0007-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0008-Doing-d1trimfile.patch
      - patches/0009-Allow-cross-compiling-for-Darwin.patch
      - patches/0010-Fix-TZPATH-on-windows.patch
      - patches/0011-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
      - patches/0012-Unvendor-bzip2.patch
      - patches/0013-Unvendor-libffi.patch
      - patches/0014-Unvendor-tcltk.patch
      - patches/0015-unvendor-xz.patch
      - patches/0016-unvendor-zlib.patch
      - patches/0017-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0018-Unvendor-expat.patch
      - patches/0019-Remove-unused-readelf.patch
      - patches/0021-Override-configure-LIBFFI.patch
      - patches/0022-Unvendor-libmpdec.patch
    sha256: 93e583f243454e6e9e4588ca2c2662206ad961659863277afcdb96801647d640
    url: https://www.python.org/ftp/python/3.13.5/Python-3.13.5.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - clangxx_osx-arm64 14.*
  no_link: null
  number: 100
  run_exports:
    noarch:
      - python
    weak:
      - python_abi 3.13.* *_cp313
  script_env:
    - CONDA_FORGE=no
    - PY_GIL_DISABLED=no
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
  string: h2eb94d5_100_cp313
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_2
    - clang-14 14.0.6 default_h1b80db6_2
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_2
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - gettext 0.21.0 hbdbcc25_2
    - icu 73.1 h313beb8_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_2
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libiconv 1.16 h80987f9_3
    - libllvm14 14.0.6 h19fdd8a_4
    - libtool 2.4.7 h313beb8_0
    - libxml2 2.13.8 h0b34f26_0
    - llvm-openmp 14.0.6 hc6e5704_0
    - llvm-tools 14.0.6 h7ec7a93_4
    - make 4.3 h620ffc9_1
    - ncurses 6.4 h313beb8_0
    - pkg-config 0.29.2 h1a28f6b_0
    - sed 4.8 h1a28f6b_0
    - tapi 1100.0.11 h8754e6a_1
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libmpdec-devel 4.0.0 hca03da5_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.16 h02f6b3c_0
    - readline 8.2 h1a28f6b_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_1
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - bzip2 >=1.0.8,<2.0a0
    - expat >=2.7.1,<3.0a0
    - libffi >=3.4,<4.0a0
    - libmpdec >=4.0.0,<5.0a0
    - ncurses >=6.4,<7.0a0
    - openssl >=3.0.16,<4.0a0
    - python_abi * *_cp313
    - readline >=8.2,<9.0a0
    - sqlite >=3.45.3,<4.0a0
    - tk >=8.6.14,<8.7.0a0
    - tzdata
    - xz >=5.6.4,<6.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - python -V
    - python3 -V
    - pydoc -h
    - python3-config --help
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - test-venv/bin/python -c "import ctypes"
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @[^@]*@ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.13.5 --debug-find --trace --debug-output --debug-trycompile
      .
    - popd
    - popd
    - python run_test.py
    - test ! -f default.profraw
    - python3.1 --version
    - python -c "from ctypes import CFUNCTYPE; CFUNCTYPE(None)(id)"
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/prefix-replacement/*
  requires:
    - clang_osx-arm64 14.*
    - clangxx_osx-arm64 14.*
    - cmake-no-system
    - make
    - ninja-base
    - ripgrep
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://devguide.python.org/
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  license_url: https://docs.python.org/3/license.html
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  flow_run_id: 5392e767-7eae-4f2a-af82-6ff23f97b049
  recipe-maintainers:
    - isuruf
    - jakirkham
    - katietz
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/python-feedstock.git
  sha: d733a67c4dfdcb9e32be85ad20963eb4f6f38156
  skip-lints:
    - license_file_overspecified
