# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_97dr4u6nc1/clone/recipe, last modified Mon Aug 18 06:25:27 2025
# ------------------------------------------------

package:
  name: jaraco.classes
  version: 3.4.0
source:
  sha256: 47a024b51d0239c0dd8c8540c6c7f484be3b8fcf0b2d85c13825780d3b3f3acd
  url: https://pypi.org/packages/source/j/jaraco.classes/jaraco.classes-3.4.0.tar.gz
build:
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_97dr4u6nc1/croot/jaraco.classes_1755516335437/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.7.15 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 19.1.7 hb09ecce_3
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.17 h4ee41c1_0
    - packaging 25.0 py313hca03da5_0
    - pip 25.1 pyhc872135_2
    - python 3.13.5 h2eb94d5_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.3 h0b18652_0
    - setuptools 78.1.1 py313hca03da5_0
    - setuptools-scm 8.3.1 py313hca03da5_1
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - more-itertools
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - python -c "import jaraco.classes.properties as p; assert hasattr(p, 'NonDataProperty')"
    - pytest -v --color=yes test_jaraco_classes.py
  files:
    - test_jaraco_classes.py
  imports:
    - jaraco
    - jaraco.classes
    - jaraco.classes.ancestry
    - jaraco.classes.meta
    - jaraco.classes.properties
  requires:
    - pip
    - pytest
about:
  description: 'jaraco.classes provides additional routines for obtaining the class
    names of an object and its parent classes,

    some useful metaclasses and methods for class properties

    '
  dev_url: https://github.com/jaraco/jaraco.classes
  doc_url: https://jaracoclasses.readthedocs.io
  home: https://github.com/jaraco/jaraco.classes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Utility functions for Python class constructs
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9792082e-5de3-4b18-abf8-bc3d02ecbd03
  recipe-maintainers:
    - carlodri
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/jaraco.classes-feedstock.git
  sha: f8b1ad2f58f061c708bb337cf2b9633e50727e4d
