# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_58oo0tj7ck/clone/recipe, last modified Fri Jul 25 12:29:42 2025
# ------------------------------------------------

package:
  name: menuinst
  version: 2.3.1
source:
  sha256: aaf1b141b78c3f193a968e01ea8ba8a9d25ab08c938f326437114fe108871280
  url: https://github.com/conda/menuinst/archive/2.3.1.tar.gz
build:
  missing_dso_whitelist:
    - '**/libswift*'
  number: '0'
  script:
    - /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_58oo0tj7ck/croot/menuinst_1753464591078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
      -m pip install . -vv --no-build-isolation --no-deps
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=2.3.1
  string: py313hca03da5_0
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 17.0.6 he5c5206_4
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.17 h4ee41c1_0
    - python 3.13.5 h2eb94d5_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.14 h6ba3021_1
    - tzdata 2025b h04d1e81_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 17.0.6 he5c5206_4
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.17 h4ee41c1_0
    - packaging 24.2 py313hca03da5_0
    - pip 25.1 pyhc872135_2
    - python 3.13.5 h2eb94d5_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 78.1.1 py313hca03da5_0
    - setuptools-scm 8.3.1 py313hca03da5_1
    - setuptools_scm 8.3.1 hd3eb1b0_1
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.14 h6ba3021_1
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - SP_DIR="$(python -c 'import site; print(site.getsitepackages()[0])')"
    - test -f "${SP_DIR}/menuinst/data/appkit_launcher_arm64"
    - test -f "${SP_DIR}/menuinst/data/appkit_launcher_x86_64"
    - test -f "${SP_DIR}/menuinst/data/osx_launcher_arm64"
    - test -f "${SP_DIR}/menuinst/data/osx_launcher_x86_64"
    - pytest tests/ -vvv --ignore=tests/test_schema.py --ignore=tests/test_elevation.py
  imports:
    - menuinst
    - menuinst.api
  requires:
    - conda
    - pip
    - pydantic >=2
    - pytest
    - pytest-mock
  source_files:
    - tests
about:
  description: 'This package provides cross platform menu item installation for conda
    packages.


    If a conda package ships a menuinst JSON document under $PREFIX/Menu, conda will
    invoke

    menuinst to process the JSON file and install the menu items in your operating
    system.

    The menu items are removed when the package is uninstalled.

    '
  dev_url: https://github.com/conda/menuinst/
  doc_url: https://conda.github.io/menuinst/
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause AND MIT
  license_family: BSD
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 588406cc-2b34-4652-b76a-5a0f9b83ffc2
  recipe-maintainers:
    - carlodri
    - goanpeca
    - isuruf
    - jaimergp
    - jakirkham
  remote_url: git@github.com:AnacondaRecipes/menuinst-feedstock.git
  sha: 85172bb99cdf1cc1940456a82d18f4ed62861da7
