# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_ac_4dmd4j4/clone/recipe, last modified Tue Jun 24 07:44:26 2025
# ------------------------------------------------

package:
  name: pydantic
  version: 2.11.7
source:
  sha256: d989c3c6cb79469287b1569f7447a17848c998458d49ebe294e975b9baf0f0db
  url: https://pypi.org/packages/source/p/pydantic/pydantic-2.11.7.tar.gz
build:
  number: '0'
  script: /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_ac_4dmd4j4/croot/pydantic_1750769074322/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - hatch-fancy-pypi-readme 24.1.0 py313hca03da5_0
    - hatchling 1.27.0 py313hca03da5_0
    - libcxx 17.0.6 he5c5206_3
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.16 h02f6b3c_0
    - packaging 24.2 py313hca03da5_0
    - pathspec 0.10.3 py313hca03da5_0
    - pip 25.1 pyhc872135_2
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.5 h2eb94d5_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 78.1.1 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_1
    - trove-classifiers 2024.10.14 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - annotated-types >=0.6.0
    - pydantic-core ==2.33.2
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - typing-extensions >=4.12.2
    - typing-inspection >=0.4.0
  run_constrained:
    - email-validator >=2.0.0
test:
  commands:
    - pip check
  imports:
    - pydantic
  requires:
    - pip
about:
  description: 'Data validation and settings management using python type hinting.

    See documentation doc_url for more details.

    '
  dev_url: https://github.com/pydantic/pydantic
  doc_url: https://docs.pydantic.dev/latest/
  home: https://github.com/pydantic/pydantic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ac888ad1-d30e-4d30-8e87-4eed07716869
  recipe-maintainers:
    - dgasmith
    - samuelcolvin
  remote_url: git@github.com:AnacondaRecipes/pydantic-feedstock.git
  sha: 80fe91936bdd3d78e6900235396108f7e8a95c53
