# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_95v32ztwo_/clone/recipe, last modified Tue Jun 24 09:31:11 2025
# ------------------------------------------------

package:
  name: urllib3
  version: 2.5.0
source:
  patches:
    - patches/0001-remove-dummyserver-usage-in-tests.patch
  sha256: 3fc47733c7e419d4bc3f6b3dc2b4f890bb743906a30d56ba4a5bfa4bbff92760
  url: https://pypi.io/packages/source/u/urllib3/urllib3-2.5.0.tar.gz
build:
  number: '0'
  script: /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_95v32ztwo_/croot/urllib3_1750775480393/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313hca03da5_0
requirements:
  build:
    - patch 2.7.6 h1a28f6b_1001
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - hatch-vcs 0.4.0 py313hca03da5_0
    - hatchling 1.27.0 py313hca03da5_0
    - libcxx 17.0.6 he5c5206_3
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.16 h02f6b3c_0
    - packaging 24.2 py313hca03da5_0
    - pathspec 0.10.3 py313hca03da5_0
    - pip 25.1 pyhc872135_2
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.5 h2eb94d5_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 78.1.1 py313hca03da5_0
    - setuptools-scm 8.3.1 py313hca03da5_1
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_1
    - trove-classifiers 2024.10.14 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - brotlicffi>=0.8.0
    - pysocks >=1.5.6,<2.0,!=1.5.7
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - h2 >=4,<5
    - zstandard>=0.18.0
test:
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('urllib3')=='2.5.0')"
    - cd test && pytest -v test_collections.py test_compatibility.py test_connection.py
      test_connectionpool.py test_exceptions.py test_fields.py test_filepost.py test_http2_connection.py
      test_no_ssl.py test_poolmanager.py test_proxymanager.py test_queue_monkeypatch.py
      test_response.py test_retry.py test_ssl.py test_util.py test_wait.py tz_stub.py
  imports:
    - urllib.parse
    - urllib3
    - urllib3.connection
    - urllib3.contrib
    - urllib3.http2
    - urllib3.util
  requires:
    - h2 >=4,<5
    - pip
    - pytest >=8.3.4
    - trio >=0.27.0
    - trustme >=1.2.1
  source_files:
    - dummyserver
    - test
about:
  description: 'urllib3 is a powerful, sanity-friendly HTTP client for Python. Much
    of the

    Python ecosystem already uses urllib3. urllib3 brings many critical features

    that are missing from the Python standard libraries, such as thread safety,

    connection pooling, client side ssl/tls verification, support for gzip and

    deflate encodings, HTTP and SOCKS proxy support, helpers for retrying requests

    and dealing with HTTP redirects.

    '
  dev_url: https://github.com/urllib3/urllib3
  doc_url: https://urllib3.readthedocs.io
  home: https://urllib3.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 955139f3-26c1-466b-a232-2c6a3ad9c56a
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
    - sethmlarson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/urllib3-feedstock.git
  sha: 0e800895d95672c32e111edc5f48d9be0a8210c9
