# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: yaml-cpp
  version: 0.8.0
source:
  sha256: fbe74bbdcee21d656715688706da3c8becfd946d92cd44705cc6098bb23b3a16
  url: https://github.com/jbeder/yaml-cpp/archive/refs/tags/0.8.0.tar.gz
build:
  number: 1
  run_exports:
    - yaml-cpp >=0.8.0,<0.9.0a0
  string: h313beb8_1
requirements:
  build:
    - bzip2 1.0.8 h80987f9_5
    - c-ares 1.19.1 h80987f9_0
    - ca-certificates 2024.3.11 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - cmake 3.26.4 h5d7ac33_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.6.2 h313beb8_0
    - krb5 1.20.1 hf3e1bf2_1
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcurl 8.5.0 h3e2b118_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20230828 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h7ec7a93_3
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.10.0 h02f6b3c_2
    - libuv 1.44.2 h80987f9_0
    - llvm-tools 14.0.6 hfd8c8a6_3
    - lz4-c 1.9.4 h313beb8_0
    - ncurses 6.4 h313beb8_0
    - ninja 1.10.2 hca03da5_5
    - ninja-base 1.10.2 h525c30c_5
    - openssl 3.0.13 h1a28f6b_0
    - python 3.12.3 h99e199e_0
    - readline 8.2 h1a28f6b_0
    - rhash 1.4.3 h02f6b3c_0
    - sqlite 3.45.3 h80987f9_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2024a h04d1e81_0
    - xz 5.4.6 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
    - zstd 1.5.5 hd90d995_0
  host:
    - libcxx 14.0.6 h848a8c0_0
  run:
    - libcxx >=14.0.6
test:
  commands:
    - test -f $PREFIX/lib/libyaml-cpp.dylib
    - test/test.sh
  files:
    - test
  requires:
    - clang_osx-arm64 14.*
    - clangxx_osx-arm64 14.*
    - cmake
    - ninja
about:
  description: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2
    spec.
  dev_url: https://github.com/jbeder/yaml-cpp
  doc_url: https://github.com/jbeder/yaml-cpp.wiki.git
  home: https://github.com/jbeder/yaml-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 605fe4ce-8db9-49d9-9a49-2710dd92c443
  recipe-maintainers:
    - allanleal
    - marcelotrevisani
    - seanyen
    - tadeu
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/yaml-cpp-feedstock.git
  sha: beb9361a150f2a91c77bd0504cd052f49b0e3ad7
