# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_b0jst6be2v/clone/recipe, last modified Mon Jul 21 02:56:18 2025
# ------------------------------------------------

package:
  name: cryptography
  version: 45.0.5
source:
  sha256: 72e76caa004ab63accdf26023fccd1d087f6d90ec6048ff33ad0445abf7f605a
  url: https://pypi.io/packages/source/c/cryptography/cryptography-45.0.5.tar.gz
build:
  number: '0'
  script:
    - export OPENSSL_DIR=$PREFIX
    - /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_b0jst6be2v/croot/cryptography_1753084599326/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
      -m pip install . -vv --no-deps --no-build-isolation
  string: py313hace6d20_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h69e4071_26
    - clang 14.0.6 hca03da5_2
    - clang-14 14.0.6 default_h1b80db6_2
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_2
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 hac4b543_26
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_2
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - llvm-tools 14.0.6 h7ec7a93_4
    - rust 1.87.0 h313beb8_0
    - rust_osx-arm64 1.87.0 h313beb8_0
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - cffi 1.17.1 py313h3eb5a62_1
    - expat 2.7.1 h313beb8_0
    - libcxx 17.0.6 he5c5206_4
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - maturin 1.8.6 py313h2aea54e_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.16 h02f6b3c_0
    - pip 25.1 pyhc872135_2
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.13.5 h2eb94d5_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 78.1.1 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.14 h6ba3021_1
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - cffi >=1.14
    - openssl >=3.0.16,<4.0a0
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - bcrypt >=3.1.5
test:
  commands:
    - pip check
    - pytest -k "not (test_x509_csr_extensions or test_no_leak_free or test_no_leak_no_malloc
      or test_leak or test_create_certificate_with_extensions or test_ec_derive_private_key
      or test_ec_private_numbers_private_key or test_create_ocsp_request or test_write_pkcs12_key_and_certificates
      or test_errors or test_ec_private_numbers_private_key or test_create_crl_with_idp
      or test_no_leak_gc or test_x25519_pubkey_from_private_key)" tests
  requires:
    - certifi >=2024
    - cryptography-vectors 45.0.5.*
    - pip
    - pretend >=0.7
    - pytest >=7.4.0
    - pytest-benchmark >=4.0
    - pytest-xdist >=3.5.0
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'Cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces to

    common cryptographic algorithms such as symmetric ciphers, message digests,

    and key derivation functions.

    '
  dev_url: https://github.com/pyca/cryptography
  doc_url: https://cryptography.io/
  home: https://github.com/pyca/cryptography
  license: Apache-2.0 OR BSD-3-Clause
  license_family: OTHER
  license_file:
    - LICENSE
    - LICENSE.APACHE
    - LICENSE.BSD
  summary: Provides cryptographic recipes and primitives to Python developers
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b02da027-f0b7-4a4e-b840-21e21ccca7df
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cryptography-feedstock.git
  sha: 80e7f541c2b45e7ad719b4dfd0c9d618c91e37e1
