# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /Users/builder/cbouss/perseverance-python-buildout/aggregate/conda-content-trust-feedstock/recipe, last modified Tue Oct  8 11:27:24 2024
# ------------------------------------------------

package:
  name: conda-content-trust
  version: 0.2.0
source:
  fn: conda-content-trust-0.2.0.tar.gz
  sha256: ded769f69a0491bd1e002ce949a332ae5a47a60ce733adb8a724802c8fdfe02b
  url: https://github.com/conda/conda-content-trust/archive/0.2.0.tar.gz
build:
  entry_points:
    - conda-content-trust = conda_content_trust.cli:cli
  number: '1'
  script: /Users/builder/cbouss/perseverance-python-buildout/croot/conda-content-trust_1728603284288/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313hca03da5_1
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.9.24 hca03da5_0
    - expat 2.6.3 h313beb8_0
    - hatch-vcs 0.3.0 py313hca03da5_1
    - hatchling 1.25.0 py313hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - packaging 24.1 py313hca03da5_0
    - pathspec 0.10.3 py313hca03da5_0
    - pip 24.2 py313hca03da5_0
    - pluggy 1.0.0 py313hca03da5_1
    - python 3.13.0 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 75.1.0 py313hca03da5_0
    - setuptools-scm 8.1.0 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - trove-classifiers 2023.10.18 py313hca03da5_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py313hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - cryptography >=41
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - conda-content-trust --help
  imports:
    - conda_content_trust
    - conda_content_trust.authentication
    - conda_content_trust.common
    - conda_content_trust.root_signing
    - conda_content_trust.signing
  requires:
    - pip
about:
  dev_url: https://github.com/conda/conda-content-trust
  doc_url: https://github.com/conda/conda-content-trust/blob/main/README.md
  home: https://github.com/conda/conda-content-trust
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Signing and verification tools for conda
extra:
  copy_test_source_files: true
  final: true
