# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /Users/builder/cbouss/buildout/aggregate/pydantic-settings-feedstock/recipe, last modified Thu Jan  2 11:15:29 2025
# ------------------------------------------------

package:
  name: pydantic-settings
  version: 2.6.1
source:
  sha256: e0f92546d8a9923cb8941689abf85d6601a8c19a23e97a34b2964a2e3f813ca0
  url: https://pypi.io/packages/source/p/pydantic-settings/pydantic_settings-2.6.1.tar.gz
build:
  number: '0'
  script: /Users/builder/cbouss/buildout/croot/pydantic-settings_1735843952737/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.11.26 hca03da5_0
    - expat 2.6.4 h313beb8_0
    - hatchling 1.27.0 py313hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - packaging 24.2 py313hca03da5_0
    - pathspec 0.10.3 py313hca03da5_0
    - pip 24.2 py313hca03da5_0
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.1 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 75.1.0 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - trove-classifiers 2024.10.14 py313hca03da5_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py313hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - pydantic >=2.7.0
    - python >=3.13,<3.14.0a0
    - python-dotenv >=0.21.0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - azure-identity >=1.16.0
    - azure-keyvault-secrets >=4.8.0
    - pyyaml >=6.0.1
    - tomli >=2.0.1
test:
  commands:
    - pip check
  imports:
    - pydantic_settings
  requires:
    - pip
about:
  description: 'Pydantic Settings provides optional Pydantic features for loading
    a settings or config class from environment

    variables or secrets files.

    '
  dev_url: https://github.com/pydantic/pydantic-settings
  doc_url: https://docs.pydantic.dev/latest/usage/pydantic_settings
  home: https://github.com/pydantic/pydantic-settings
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Settings management using Pydantic
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - fhoehle
    - jan-janssen
