# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_084du80plg/clone/recipe, last modified Tue Apr 30 16:01:37 2024
# ------------------------------------------------

package:
  name: zlib
  version: 1.2.13
source:
  patches:
    - cmake-pkg-config.patch
  sha256: b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30
  url: https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.gz
build:
  number: '1'
  run_exports:
    - zlib >=1.2.13,<1.3.0a0
  string: h18a0788_1
requirements:
  build:
    - clang_bootstrap_osx-arm64 14.0.6 h1d3d883_0
    - cmake-no-system 3.25.3 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - make 4.3 h620ffc9_1
    - patch 2.7.6 h1a28f6b_1001
  host:
    - ripgrep 13.0.0 h15d1925_2
  run: []
test:
  commands:
    - test -f ${PREFIX}/include/zlib.h
    - test -f ${PREFIX}/lib/libz.a
    - test -f ${PREFIX}/lib/libz.dylib
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib
  doc_url: https://zlib.net/manual.html
  home: https://zlib.net/
  license: Zlib
  license_family: Other
  license_file: zlib.h
  summary: Massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 081cbdae-2c6d-4b2d-8cda-b861b89ea3d4
  recipe-maintainers:
    - groutr
    - mingwandroid
    - msarahan
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/zlib-feedstock.git
  sha: b57c9c8be0d78d53293e72a59c2e5dc3462b2c90
