# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: libcurl
  version: 8.14.1
source:
  sha256: 5760ed3c1a6aac68793fc502114f35c3e088e8cd5c084c2d044abdf646ee48fb
  url: https://curl.se/download/curl-8.14.1.tar.bz2
build:
  ignore_run_exports:
    - libkrb5
  number: 1
  run_exports:
    - libcurl >=8.14.1,<9.0a0
  string: hcdd2897_1
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h69e4071_26
    - clang 14.0.6 hca03da5_2
    - clang-14 14.0.6 default_h1b80db6_2
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_2
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 hac4b543_26
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_2
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - llvm-tools 14.0.6 h7ec7a93_4
    - macosx_deployment_target_osx-arm64 11.1 had524d6_1
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host:
    - c-ares 1.19.1 h80987f9_0
    - ca-certificates 2025.2.25 hca03da5_0
    - libcxx 17.0.6 he5c5206_4
    - libev 4.33 h1a28f6b_1
    - libkrb5 1.21.3 h73ed823_3
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.11.1 h3e2b118_0
    - lmdb 0.9.29 hc377ac9_0
    - lz4-c 1.9.4 h313beb8_1
    - openssl 3.0.17 h4ee41c1_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
    - zstd 1.5.6 hfb09047_0
  run:
    - __osx >=11.1
    - libnghttp2 >=1.57.0
    - libnghttp2 >=1.57.0,<2.0a0
    - libssh2 >=1.10.0
    - libssh2 >=1.11.1,<2.0a0
    - openssl >=3.0.17,<4.0a0
    - zlib >=1.2.13,<1.3.0a0
    - zstd >=1.5.6,<1.6.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - CURL_SSL_BACKENDS=$(curl-config --ssl-backends)
    - if ! echo $CURL_SSL_BACKENDS | grep -q "OpenSSL"; then exit 1; fi
    - if ! echo $CURL_SSL_BACKENDS | grep -q "Secure Transport"; then exit 1; fi
about:
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  dev_url: https://github.com/curl/curl
  doc_url: https://curl.se/docs/
  home: https://curl.se/
  license: curl
  license_family: MIT
  license_url: https://curl.se/docs/copyright.html
  summary: tool and library for transferring data with URL syntax
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 31735e01-bff2-4a68-90fb-df715ede684a
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
  remote_url: git@github.com:AnacondaRecipes/curl-feedstock.git
  sha: d6f5974f38abe27302536af9c355b2c70848a3ea
