# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: anaconda-auth
  version: 0.8.6
source:
  git_rev: v0.8.6
  git_url: https://github.com/anaconda/anaconda-auth.git
build:
  number: 0
  script: python -m pip install . --no-deps --no-build-isolation --ignore-installed
    --no-cache-dir -vv
  string: py313hca03da5_0
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - c-ares 1.19.1 h80987f9_0
    - ca-certificates 2025.2.25 hca03da5_0
    - curl 8.12.1 h3e2b118_0
    - expat 2.7.1 h313beb8_0
    - gettext 0.21.0 hbdbcc25_2
    - git 2.45.2 pl5340hae58ea7_1
    - icu 73.1 h313beb8_0
    - krb5 1.20.1 hf3e1bf2_1
    - libcurl 8.12.1 hde089ae_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20230828 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libiconv 1.16 h80987f9_3
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.11.1 h3e2b118_0
    - libxml2 2.13.8 h0b34f26_0
    - llvm-openmp 14.0.6 hc6e5704_0
    - lz4-c 1.9.4 h313beb8_1
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.16 h02f6b3c_0
    - pcre2 10.42 hb066dcc_1
    - perl 5.40.2 0_h80987f9_perl5
    - tk 8.6.14 h6ba3021_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
    - zstd 1.5.6 hfb09047_0
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - hatch-vcs 0.4.0 py313hca03da5_0
    - hatchling 1.27.0 py313hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.16 h02f6b3c_0
    - packaging 24.2 py313hca03da5_0
    - pathspec 0.10.3 py313hca03da5_0
    - pip 25.1 pyhc872135_2
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.2 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 78.1.1 py313hca03da5_0
    - setuptools-scm 8.3.1 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - trove-classifiers 2024.10.14 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - anaconda-cli-base >=0.5.2
    - cryptography >=3.4.0
    - keyring
    - pkce
    - pydantic
    - pyjwt
    - python >=3.13,<3.14.0a0
    - python-dotenv
    - python_abi 3.13.* *_cp313
    - requests
    - semver <4
  run_constrained:
    - anaconda-cloud-auth >=0.8.2
    - conda >=23.9.0
    - conda-token >=0.6.0
test:
  commands:
    - pip check
    - python -c "from anaconda_auth import __version__; assert __version__ == '0.8.6'"
  imports:
    - anaconda_auth
  requires:
    - pip
  source_files:
    - pyproject.toml
about:
  description: 'A client library for Anaconda.cloud APIs to authenticate and securely
    store API keys.

    This package also provides a requests client class that handles loading the API
    key

    for requests made to Anaconda Cloud services.

    '
  dev_url: https://github.com/anaconda/anaconda-auth
  doc_url: https://anaconda.github.io/anaconda-auth/
  home: https://anaconda.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client auth library for Anaconda.cloud APIs
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: c9828c15-d3f4-4dc3-b4ed-9073e6f90ae0
  recipe-maintainers:
    - albertdefusco
    - mattkram
  remote_url: git@github.com:AnacondaRecipes/anaconda-cloud-auth-feedstock.git
  sha: db12db92c88b355fa8f6b25ac8fc36ee80b0703d
