# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_ddeo65t9li/clone/recipe, last modified Thu Feb 13 11:37:49 2025
# ------------------------------------------------

package:
  name: xz
  version: 5.6.4
source:
  sha256: 269e3f2e512cbd3314849982014dc199a7b2148cf5c91cedc6db629acdf5e09b
  url: https://github.com/tukaani-project/xz/releases/download/v5.6.4/xz-5.6.4.tar.gz
build:
  number: '1'
  run_exports:
    - xz >=5.6.4,<6.0a0
  string: h80987f9_1
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_2
    - clang-14 14.0.6 default_h1b80db6_2
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_2
    - cmake-no-system 3.25.3 h313beb8_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_2
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - llvm-tools 14.0.6 h7ec7a93_4
    - ninja-base 1.12.1 h48ca7d4_0
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host: []
  run: []
test:
  commands:
    - xz --help
    - unxz --help
    - lzma --help
    - test -f ${PREFIX}/include/lzma.h
    - test -f ${PREFIX}/lib/cmake/liblzma/liblzma-config.cmake
    - test -f ${PREFIX}/lib/pkgconfig/liblzma.pc
    - test -f `pkg-config --variable=libdir --dont-define-prefix liblzma`/liblzma${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/liblzma.a
    - test -f ${PREFIX}/lib/liblzma${SHLIB_EXT}
    - test -f ${PREFIX}/lib/liblzma.5${SHLIB_EXT}
    - conda inspect linkages -p $PREFIX $PKG_NAME
    - conda inspect objects -p $PREFIX $PKG_NAME
  requires:
    - conda-build
    - pkg-config
about:
  description: 'XZ Utils is free general-purpose data compression software with a
    high

    compression ratio. XZ Utils were written for POSIX-like systems, but also

    work on some not-so-POSIX systems.

    '
  dev_url: https://github.com/tukaani-project/xz
  doc_url: https://tukaani.org/xz/#_documentation
  home: https://tukaani.org/xz/
  license: LGPL-2.1-or-later and GPL-2.0-or-later and 0BSD
  license_family: GPL2
  license_file: COPYING
  summary: Data compression software with high compression ratio
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: dd3c0d98-5f55-4ae0-82bf-579bdb60fda2
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - nehaljwani
    - ocefpaf
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/xz-feedstock.git
  sha: 455f54e9b06b1d5e8333c89e46da9cdba1c3ea61
