# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_92peotmhak/clone/recipe, last modified Thu May  2 08:46:58 2024
# ------------------------------------------------

package:
  name: pcre2
  version: '10.42'
source:
  sha256: a8e52a9bd1bca8f51c5c24823adc2a99acb12288e289a6507090c1a4a4815010
  url: https://github.com/PCRE2Project/pcre2/archive/refs/tags/pcre2-10.42.tar.gz
build:
  number: '1'
  run_exports:
    - pcre2 >=10.42,<10.43.0a0
  string: hb066dcc_1
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - c-ares 1.19.1 h80987f9_0
    - ca-certificates 2024.3.11 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - cmake 3.26.4 h5d7ac33_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.6.2 h313beb8_0
    - krb5 1.20.1 hf3e1bf2_1
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcurl 8.5.0 h3e2b118_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20230828 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h7ec7a93_3
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.10.0 h02f6b3c_3
    - libuv 1.44.2 h80987f9_0
    - llvm-tools 14.0.6 hfd8c8a6_3
    - lz4-c 1.9.4 h313beb8_1
    - ncurses 6.4 h313beb8_0
    - ninja 1.10.2 hca03da5_5
    - ninja-base 1.10.2 h525c30c_5
    - openssl 3.0.13 h1a28f6b_1
    - python 3.12.3 h99e199e_0
    - readline 8.2 h1a28f6b_0
    - rhash 1.4.3 h02f6b3c_0
    - sqlite 3.45.3 h80987f9_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2024a h04d1e81_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
    - zstd 1.5.5 hd90d995_1
  host:
    - bzip2 1.0.8 h80987f9_6
    - zlib 1.2.13 h18a0788_1
  run:
    - bzip2 >=1.0.8,<2.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - pcre2test --version
    - pcre2grep --version
    - pcre2-config --version
    - test -f ${PREFIX}/include/pcre2.h
    - test -f ${PREFIX}/include/pcre2posix.h
    - test -f ${PREFIX}/lib/libpcre2-posix${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libpcre2-posix.3${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libpcre2-8${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libpcre2-8.0${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libpcre2-16${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libpcre2-16.0${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libpcre2-32${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libpcre2-32.0${SHLIB_EXT}
    - test -f ${PREFIX}/lib/pkgconfig/libpcre2-8.pc
    - test -f ${PREFIX}/lib/pkgconfig/libpcre2-16.pc
    - test -f ${PREFIX}/lib/pkgconfig/libpcre2-32.pc
    - test -f ${PREFIX}/lib/pkgconfig/libpcre2-posix.pc
about:
  description: 'The PCRE library is a set of functions that implement regular expression
    pattern matching

    using the same syntax and semantics as Perl 5. PCRE has its own native API, as
    well as a set of

    wrapper functions that correspond to the POSIX regular expression API. The PCRE
    library is

    free, even for building proprietary software.

    '
  dev_url: https://github.com/PCRE2Project/pcre2
  doc_url: https://www.pcre.org/current/doc/html/
  home: https://www.pcre.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENCE
  summary: Regular expression pattern matching using Perl 5 syntax and semantics.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 929087e0-b5dd-4f70-9f91-a132bb98ca7d
  recipe-maintainers:
    - dfornika
    - mariusvniekerk
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/pcre2-feedstock.git
  sha: 4bb34882a00cb1cdb7808a2f2a373bc9008a5715
