# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_08m4xcbj7q/clone/recipe, last modified Fri Mar  7 11:44:21 2025
# ------------------------------------------------

package:
  name: anaconda-cli-base
  version: 0.5.2
source:
  sha256: 96ba616ae7091ef2cb5bd473dc164c68e2328ba98b70ce5afbfe7ad3123c8081
  url: https://pypi.io/packages/source/a/anaconda-cli-base/anaconda_cli_base-0.5.2.tar.gz
build:
  entry_points:
    - anaconda = anaconda_cli_base.cli:app
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_08m4xcbj7q/croot/anaconda-cli-base_1741369478940/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.6.4 h313beb8_0
    - hatch-vcs 0.3.0 py313hca03da5_1
    - hatchling 1.27.0 py313hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.16 h02f6b3c_0
    - packaging 24.2 py313hca03da5_0
    - pathspec 0.10.3 py313hca03da5_0
    - pip 25.0 py313hca03da5_0
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.2 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 75.8.0 py313hca03da5_0
    - setuptools-scm 8.1.0 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - trove-classifiers 2024.10.14 py313hca03da5_0
    - tzdata 2025a h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - click
    - pydantic-settings >=2.3
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
    - readchar
    - rich
    - tomli
    - typer
  run_constrained:
    - anaconda-client >=1.13.0
    - anaconda-cloud-cli >=0.3.0
test:
  commands:
    - pip check
    - anaconda -h
    - anaconda -V
    - python -c "from anaconda_cli_base import __version__; assert __version__ ==
      \"0.5.2\""
    - python -c "from importlib.metadata import version; assert(version('anaconda-cli-base')=='0.5.2')"
    - pytest -v tests
  imports:
    - anaconda_cli_base
  requires:
    - pip
    - pytest
    - pytest-mock
    - types-requests
  source_files:
    - tests
about:
  description: A base CLI entrypoint supporting Anaconda CLI plugins
  dev_url: https://pypi.org/project/anaconda-cli-base/
  doc_url: https://pypi.org/project/anaconda-cli-base/
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A base CLI entrypoint supporting Anaconda CLI plugins
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 08f00b8f-7394-4179-b10b-1aeac4de0d14
  recipe-maintainers:
    - albertdefusco
    - mattkram
  remote_url: git@github.com:AnacondaRecipes/anaconda-cli-base-feedstock.git
  sha: 945811f50b8db47f54b1ddc3687d07d1981207ef
