# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_5b9sxgbx20/clone/recipe, last modified Tue Oct  1 03:04:52 2024
# ------------------------------------------------

package:
  name: python_abi
  version: '3.13'
build:
  number: '0'
  string: 0_cp313
requirements:
  build: []
  run: []
  run_constrained:
    - python 3.13.* *_cp313
test:
  commands:
    - echo "hello"
about:
  description: Metapackage to select python implementation
  dev_url: https://github.com/conda-forge/python_abi-feedstock
  doc_url: https://github.com/conda-forge/python_abi-feedstock
  home: https://github.com/conda-forge/python_abi-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Metapackage to select python implementation
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 5bb7e5aa-001c-4497-aa7a-fb414ed8e4eb
  recipe-maintainers:
    - chrisburr
    - isuruf
  remote_url: git@github.com:AnacondaRecipes/python_abi-feedstock.git
  sha: 89c3ccea9ce729ea99d793014fd1ca6946e22856
