# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: simdjson
  version: 3.10.1
source:
  sha256: 1e8f881cb2c0f626c56cd3665832f1e97b9d4ffc648ad9e1067c134862bba060
  url: https://github.com/simdjson/simdjson/archive/v3.10.1.tar.gz
build:
  number: 0
  run_exports:
    - simdjson >=3.10.1,<3.11.0a0
  string: h48ca7d4_0
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - c-ares 1.19.1 h80987f9_0
    - ca-certificates 2024.11.26 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - cmake 3.26.4 h5d7ac33_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.6.4 h313beb8_0
    - krb5 1.20.1 hf3e1bf2_1
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcurl 8.9.1 h3e2b118_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20230828 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - libmpdec 4.0.0 h80987f9_0
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.11.1 h3e2b118_0
    - libuv 1.48.0 h80987f9_0
    - llvm-tools 14.0.6 h7ec7a93_4
    - lz4-c 1.9.4 h313beb8_1
    - ncurses 6.4 h313beb8_0
    - ninja 1.12.1 hca03da5_0
    - ninja-base 1.12.1 h48ca7d4_0
    - openssl 3.0.15 h80987f9_0
    - python 3.13.1 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - rhash 1.4.3 h02f6b3c_0
    - sqlite 3.45.3 h80987f9_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024b h04d1e81_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
    - zstd 1.5.6 hfb09047_0
  host:
    - libcxx 14.0.6 h848a8c0_0
  run:
    - libcxx >=14.0.6
test:
  commands:
    - test -f "${PREFIX}/include/simdjson.h"
    - test -f "${PREFIX}/lib/libsimdjson${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/cmake/simdjson/simdjson-config.cmake"
    - cmake -G Ninja -S test/ -B build/ -D TEST_TARGET=simdjson ${CMAKE_ARGS}
    - cmake --build build/
    - cmake --build build --target test
  files:
    - test/*
  requires:
    - clangxx_osx-arm64 14.*
    - cmake
    - ninja
about:
  description: 'JSON is everywhere on the Internet.

    Servers spend a *lot* of time parsing it. We need a fresh approach.

    The simdjson library uses commonly available SIMD instructions and

    microparallel algorithms to parse JSON 2.5x faster than anything else out there.

    '
  dev_url: https://github.com/simdjson/simdjson/
  doc_url: https://simdjson.github.io/simdjson/
  home: https://simdjson.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Parsing gigabytes of JSON per second
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 47b0f2c1-724c-45d4-97e0-2f6ecbd08242
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - elbaro
  remote_url: git@github.com:AnacondaRecipes/simdjson-feedstock.git
  sha: 751e747ff65ed7f4c599e297a43a84ae810be04c
