# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_bdid71leqg/clone/recipe, last modified Tue Jul 29 06:27:18 2025
# ------------------------------------------------

package:
  name: jsonpointer
  version: 3.0.0
source:
  sha256: 2b2d729f2091522d61c3b31f82e11870f60b68f43fbc705cb76bf4b832af59ef
  url: https://pypi.org/packages/source/j/jsonpointer/jsonpointer-3.0.0.tar.gz
build:
  number: '0'
  script: /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_bdid71leqg/croot/jsonpointer_1753788445166/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps --no-build-isolation -vvv
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 17.0.6 he5c5206_4
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.17 h4ee41c1_0
    - pip 25.1 pyhc872135_2
    - python 3.13.5 h2eb94d5_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 78.1.1 py313hca03da5_0
    - sqlite 3.50.2 h79febb2_1
    - tk 8.6.14 h6ba3021_1
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('jsonpointer')=='3.0.0')"
    - pytest -vv tests.py
  imports:
    - jsonpointer
  requires:
    - pip
    - pytest
    - python >=3.13,<3.14.0a0
  source_files:
    - tests.py
about:
  description: Library to resolve JSON Pointers according to RFC 6901
  dev_url: https://github.com/stefankoegl/python-json-pointer
  doc_url: https://python-json-pointer.readthedocs.io
  home: https://github.com/stefankoegl/python-json-pointer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Identify specific nodes in a JSON document (RFC 6901)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: bd0b240d-662b-40dd-a370-decfb7d486f3
  recipe-maintainers:
    - anguslees
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/jsonpointer-feedstock.git
  sha: 6fc82f746c483b32916955f3e32a700dd82138ba
