# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_d9xusw0yil/clone/recipe, last modified Tue Apr 29 09:32:34 2025
# ------------------------------------------------

package:
  name: ruamel.yaml.clib
  version: 0.2.12
source:
  sha256: 6c8fbb13ec503f99a91901ab46e0b07ae7941cd527393187039aec586fdfd36f
  url: https://pypi.io/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-0.2.12.tar.gz
build:
  ignore_run_exports:
    - python
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_d9xusw0yil/croot/ruamel.yaml.clib_1745937162586/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313h80987f9_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_2
    - clang-14 14.0.6 default_h1b80db6_2
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_2
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_2
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - llvm-tools 14.0.6 h7ec7a93_4
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.16 h02f6b3c_0
    - pip 25.0 py313hca03da5_0
    - python 3.13.2 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 75.8.0 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2025a h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
  imports:
    - _ruamel_yaml
  requires:
    - pip
    - ruamel.yaml
about:
  description: 'This package was split of from ruamel.yaml, so that ruamel.yaml can
    be build as a universal wheel.

    Apart from the C code seldom changing, and taking a long time to compile for all
    platforms, this allows

    installation of the .so on Linux systems under /usr/lib64/pythonX.Y (without a
    .pth file or a ruamel

    directory) and the Python code for ruamel.yaml under /usr/lib/pythonX.Y.

    '
  dev_url: https://sourceforge.net/projects/ruamel-yaml-clib/
  doc_url: https://yaml.readthedocs.io
  home: https://sourceforge.net/projects/ruamel-yaml-clib/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C version of reader, parser and emitter for ruamel.yaml derived from libyaml
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: d9b6761f-b0b8-401e-a56f-300df18f29b3
  recipe-maintainers:
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/ruamel.yaml.clib-feedstock.git
  sha: ab0357f3f30cc0bc1173990a265999156d1ae324
