# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_77d995f1ra/clone/recipe, last modified Thu May  2 15:14:30 2024
# ------------------------------------------------

package:
  name: reproc
  version: 14.2.4
source:
  - patches:
      - apple_gettime.patch
    sha256: 55c780f7faa5c8cabd83ebbb84b68e5e0e09732de70a129f6b3c801e905415dd
    url: https://github.com/DaanDeMeyer/reproc/archive/v14.2.4.tar.gz
build:
  number: '2'
  run_exports:
    - reproc >=14.2,<15.0a0
  string: h313beb8_2
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - c-ares 1.19.1 h80987f9_0
    - ca-certificates 2024.3.11 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - cmake 3.26.4 h5d7ac33_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.6.2 h313beb8_0
    - krb5 1.20.1 hf3e1bf2_1
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcurl 8.5.0 h3e2b118_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20230828 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h7ec7a93_3
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.10.0 h02f6b3c_3
    - libuv 1.44.2 h80987f9_0
    - llvm-tools 14.0.6 hfd8c8a6_3
    - lz4-c 1.9.4 h313beb8_1
    - ncurses 6.4 h313beb8_0
    - ninja 1.10.2 hca03da5_5
    - ninja-base 1.10.2 h525c30c_5
    - openssl 3.0.13 h1a28f6b_1
    - python 3.12.3 h99e199e_0
    - readline 8.2 h1a28f6b_0
    - rhash 1.4.3 h02f6b3c_0
    - sqlite 3.45.3 h80987f9_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2024a h04d1e81_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
    - zstd 1.5.5 hd90d995_1
  run: []
about:
  dev_url: https://github.com/DaanDeMeyer/reproc
  doc_src_url: https://github.com/DaanDeMeyer/reproc
  doc_url: https://github.com/DaanDeMeyer/reproc#reproc
  home: https://github.com/DaanDeMeyer/reproc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: reproc (Redirected Process) is a cross-platform C/C++ library that simplifies
    starting, stopping and communicating with external programs.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 77215bd3-5c99-400c-a45e-d4be0c152286
  recipe-maintainers:
    - DaanDeMeyer
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/reproc-feedstock.git
  sha: 39002db99a2955d830945b69264da997a7bf10aa
