# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_b5py2dr5ag/clone/recipe, last modified Mon Jan  6 10:54:25 2025
# ------------------------------------------------

package:
  name: brotlicffi
  version: 1.0.9.2
source:
  sha256: 0c248a68129d8fc6a217767406c731e498c3e19a7be05ea0a90c3c86637b7d96
  url: https://pypi.io/packages/source/b/brotlicffi/brotlicffi-1.0.9.2.tar.gz
build:
  number: '1'
  script: /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_b5py2dr5ag/croot/brotlicffi_1736182482518/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: py313h313beb8_1
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_2
    - clang-14 14.0.6 default_h1b80db6_2
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_2
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_2
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - llvm-tools 14.0.6 h7ec7a93_4
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.11.26 hca03da5_0
    - cffi 1.17.1 py313h3eb5a62_0
    - expat 2.6.4 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - pip 24.2 py313hca03da5_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.13.1 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 75.1.0 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py313hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - cffi >=1.0.0
    - libcxx >=14.0.6
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
  imports:
    - brotlicffi
  requires:
    - pip
about:
  home: https://github.com/python-hyper/brotlicffi
  license: MIT
  license_file: LICENSE
  summary: Python CFFI bindings to the Brotli library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b563351b-8c43-4eeb-b505-a72cea61c16b
  recipe-maintainers:
    - katietz
    - sarthakpati
    - sethmlarson
  remote_url: git@github.com:AnacondaRecipes/brotlicffi-feedstock.git
  sha: 3f4e921412296146ece83c47c30b865765262440
