# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_069us6c53_/clone/recipe, last modified Thu Dec 12 15:34:55 2024
# ------------------------------------------------

package:
  name: cpp-expected
  version: 1.1.0
source:
  - sha256: 1db357f46dd2b24447156aaf970c4c40a793ef12a8a9c2ad9e096d9801368df6
    url: https://github.com/TartanLlama/expected/archive/refs/tags/v1.1.0.tar.gz
build:
  number: '0'
  string: h48ca7d4_0
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - c-ares 1.19.1 h80987f9_0
    - ca-certificates 2024.11.26 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - cmake 3.26.4 h5d7ac33_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.6.4 h313beb8_0
    - krb5 1.20.1 hf3e1bf2_1
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcurl 8.9.1 h3e2b118_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20230828 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - libmpdec 4.0.0 h80987f9_0
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.11.1 h3e2b118_0
    - libuv 1.48.0 h80987f9_0
    - llvm-tools 14.0.6 h7ec7a93_4
    - lz4-c 1.9.4 h313beb8_1
    - ncurses 6.4 h313beb8_0
    - ninja 1.12.1 hca03da5_0
    - ninja-base 1.12.1 h48ca7d4_0
    - openssl 3.0.15 h80987f9_0
    - python 3.13.1 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - rhash 1.4.3 h02f6b3c_0
    - sqlite 3.45.3 h80987f9_0
    - tapi 1100.0.11 h8754e6a_1
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024b h04d1e81_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
    - zstd 1.5.6 hfb09047_0
  host:
    - libcxx 14.0.6 h848a8c0_0
  run:
    - libcxx >=14.0.6
test:
  commands:
    - test -f ${PREFIX}/include/tl/expected.hpp
    - test -f ${PREFIX}/share/cmake/tl-expected/tl-expected-config.cmake
    - test -f ${PREFIX}/share/cmake/tl-expected/tl-expected-config-version.cmake
about:
  description: C++11/14/17 std::expected with functional-style extensions
  dev_url: https://github.com/TartanLlama/expected
  doc_url: https://github.com/TartanLlama/expected#readme
  home: https://github.com/TartanLlama/expected
  license: CC0-1.0
  license_family: CC
  license_file: COPYING
  summary: C++11/14/17 std::expected with functional-style extensions
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 064a676e-1a18-4c06-98a2-1914775ed59c
  recipe-maintainers:
    - JohanMabille
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/cpp-expected-feedstock.git
  sha: 4457a27f5d09d4666580e8050590e37591484e2c
